services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      pg:
        condition: service_healthy
      memcache:
        condition: service_started
  pg:
    image: postgres:latest
    ports:
      - 45432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    env_file: .env.local
    volumes:
      - "pgdata:/data/postgres"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  memcache:
    image: memcached:latest
    ports:
      - 11211:11211

volumes:
  pgdata: